_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
PRIMARY_TO_SECONDARY:
    value:
        "1":
            - 1
            - 2
            - 3
            - 4
            - 5
            - 24
        "2":
            - 6
            - 7
            - 8
            - 9
            - 25
            - 26
        "3":
            - 10
            - 11
            - 12
            - 13
            - 14
            - 27
        "4":
            - 15
            - 28
            - 29
        "5":
            - 17
            - 18
            - 19
        "6":
            - 20
            - 21
            - 22
            - 23
        "7":
            - 30
            - 16
            - 31
        "8":
            - 32
        "9":
            - 33
batch_size:
    value: 128
data_num:
    value: 20
epochs:
    value: 20
gamma:
    value: 0.5
lr:
    value: 0.001
milestones:
    value:
        - 100
unfreeze_schedule:
    value:
        "15": 0.3
weight_decay:
    value: 0.0001
